/**
 * OpenAPI 3.1 description of the `/api/v1` surface (D8). HAND-ASSEMBLED rather
 * than generated by a zod-to-openapi dependency (CLAUDE.md "no new dependencies"
 * + the backlog/4.2 recommendation): OpenAPI 3.1 is a JSON Schema 2020-12
 * superset, so the LARGE complex schema - the document - is referenced straight
 * from the existing `toJsonSchema()` export (story 1.2, `static/schema/v1.json`)
 * with NO translation. The small, stable request/response wrappers (the report
 * resource, the create/update payloads, the RFC 9457 Problem shape) are written
 * here; hand-writing them is less code and zero dependency than wiring a
 * generator, and the document schema stays the single source of truth.
 *
 * Served at `/api/v1/openapi.json` as a PUBLIC discovery surface (no PAT): the
 * spec is the API's self-description and leaks no report data, consistent with
 * the 4.3 public `/api/v1/schema`. The endpoints it describes are all
 * bearer-authenticated (the `patBearer` security scheme, D10).
 */
import { CURRENT_SCHEMA_VERSION, toJsonSchema } from '$lib/schema';

const REPORT_STATUS = { type: 'string', enum: ['draft', 'published'] } as const;

/** The report resource as serialized by the endpoints (Dates become ISO strings over JSON). */
function reportSchema(): Record<string, unknown> {
	return {
		type: 'object',
		required: ['id', 'title', 'status', 'schemaVersion', 'document', 'createdAt', 'updatedAt'],
		properties: {
			id: { type: 'string', format: 'uuid' },
			title: { type: 'string' },
			status: REPORT_STATUS,
			schemaVersion: { type: 'integer' },
			document: { $ref: '#/components/schemas/Document' },
			publishedDocument: {
				oneOf: [{ $ref: '#/components/schemas/Document' }, { type: 'null' }]
			},
			publishedAt: { type: ['string', 'null'], format: 'date-time' },
			createdAt: { type: 'string', format: 'date-time' },
			updatedAt: { type: 'string', format: 'date-time' }
		}
	};
}

function reportSummarySchema(): Record<string, unknown> {
	return {
		type: 'object',
		required: ['id', 'title', 'status', 'updatedAt'],
		properties: {
			id: { type: 'string', format: 'uuid' },
			title: { type: 'string' },
			status: REPORT_STATUS,
			updatedAt: { type: 'string', format: 'date-time' }
		}
	};
}

/** RFC 9457 problem+json (D9), including the FR2 actionable `errors[]` (block path/field/hint). */
function problemSchema(): Record<string, unknown> {
	return {
		type: 'object',
		description: 'RFC 9457 problem details (application/problem+json).',
		required: ['type', 'title', 'status'],
		properties: {
			type: { type: 'string' },
			title: { type: 'string' },
			status: { type: 'integer' },
			detail: { type: 'string' },
			errors: {
				type: 'array',
				description:
					'Actionable validation errors (FR2): the failing block path, field, and a fix hint.',
				items: {
					type: 'object',
					required: ['path', 'message'],
					properties: {
						path: { type: 'string', description: 'e.g. sections[2].blocks[0].alt' },
						message: { type: 'string' },
						hint: { type: 'string' }
					}
				}
			}
		}
	};
}

/** The document component: the published JSON Schema export, embedded directly (no $ref rewrite needed - it is fully inlined). */
function documentComponent(): Record<string, unknown> {
	const { $schema: _dialect, ...schema } = toJsonSchema();
	void _dialect;
	return schema;
}

/** A `data_sets` row as serialized by the push endpoint (story 4.3). */
function dataSetSchema(): Record<string, unknown> {
	return {
		type: 'object',
		required: ['id', 'reportId', 'filename', 'sourceFormat', 'fields', 'injectedAt', 'storagePath'],
		properties: {
			id: { type: 'string', format: 'uuid' },
			reportId: { type: ['string', 'null'], format: 'uuid' },
			filename: { type: 'string' },
			sourceFormat: { type: 'string', enum: ['csv', 'json', 'xlsx'] },
			fields: {
				type: 'array',
				items: {
					type: 'object',
					required: ['name', 'type'],
					properties: {
						name: { type: 'string' },
						type: { type: 'string' }
					}
				}
			},
			injectedAt: { type: 'string', format: 'date-time' },
			dataAsOf: { type: ['string', 'null'], format: 'date-time' },
			storagePath: { type: 'string' }
		}
	};
}

/** A per-block binding diagnostic (FR15): block, expected field, closest match. */
function blockDiagnosticSchema(): Record<string, unknown> {
	return {
		type: 'object',
		required: ['blockId', 'blockType', 'label', 'state', 'drifts'],
		properties: {
			blockId: { type: 'string' },
			blockType: { type: 'string', enum: ['table', 'chart', 'kpi'] },
			label: { type: 'string' },
			state: { type: 'string', enum: ['bound', 'drifted', 'unresolved'] },
			drifts: {
				type: 'array',
				items: {
					type: 'object',
					required: ['expected', 'closest'],
					properties: {
						expected: { type: 'string' },
						closest: { type: ['string', 'null'] },
						distance: { type: 'integer' }
					}
				}
			}
		}
	};
}

/** The aggregate binding summary (the workspace header counts). */
function bindingSummarySchema(): Record<string, unknown> {
	return {
		type: 'object',
		required: ['total', 'bound', 'drifted', 'unresolved', 'allGreen'],
		properties: {
			total: { type: 'integer' },
			bound: { type: 'integer' },
			drifted: { type: 'integer' },
			unresolved: { type: 'integer' },
			allGreen: { type: 'boolean' }
		}
	};
}

/**
 * The data-push response (story 4.3): always the stored data set; the
 * diagnostics + summary + rebound block ids are present when the push targeted a
 * report (the auto-rebind ran), absent for an unbound push.
 */
function dataPushResponseSchema(): Record<string, unknown> {
	return {
		type: 'object',
		required: ['dataSet'],
		properties: {
			dataSet: { $ref: '#/components/schemas/DataSet' },
			diagnostics: {
				type: 'array',
				items: { $ref: '#/components/schemas/BlockDiagnostic' }
			},
			summary: { $ref: '#/components/schemas/BindingSummary' },
			rebound: { type: 'array', items: { type: 'string' } }
		}
	};
}

/**
 * The outline artifact (item 18): the bounded, reviewable structure
 * `generate_outline` returns and `generate_report` fills. The block `type` is the
 * generatable subset; the intents are one-line guidance strings.
 */
function outlineSchema(): Record<string, unknown> {
	return {
		type: 'object',
		required: ['title', 'sections'],
		properties: {
			title: { type: 'string' },
			sections: {
				type: 'array',
				items: {
					type: 'object',
					required: ['title', 'intent', 'blocks'],
					properties: {
						title: { type: 'string' },
						intent: { type: 'string' },
						blocks: {
							type: 'array',
							items: {
								type: 'object',
								required: ['type', 'intent'],
								properties: {
									type: { type: 'string', enum: ['text', 'kpi', 'table', 'chart'] },
									intent: { type: 'string' }
								}
							}
						}
					}
				}
			}
		}
	};
}

/** The `POST /reports/generate/outline` response: the outline plus its approval hash. */
function generateOutlineResponseSchema(): Record<string, unknown> {
	return {
		type: 'object',
		required: ['outline', 'outlineHash'],
		properties: {
			outline: { $ref: '#/components/schemas/Outline' },
			outlineHash: {
				type: 'string',
				description: 'The SHA-256 content hash binding a later fill to this exact outline.'
			}
		}
	};
}

/** The published-schema response (story 4.3): version, schema, examples. */
function schemaResponseSchema(): Record<string, unknown> {
	return {
		type: 'object',
		required: ['version', 'schema', 'examples'],
		properties: {
			version: { type: 'integer' },
			schema: {
				type: 'object',
				description: 'The published JSON Schema (draft 2020-12) of the current document version.'
			},
			examples: {
				type: 'object',
				required: ['minimal', 'full'],
				properties: {
					minimal: { $ref: '#/components/schemas/Document' },
					full: { $ref: '#/components/schemas/Document' }
				}
			}
		}
	};
}

function problemResponse(description: string): Record<string, unknown> {
	return {
		description,
		content: { 'application/problem+json': { schema: { $ref: '#/components/schemas/Problem' } } }
	};
}

function reportResponse(description: string): Record<string, unknown> {
	return {
		description,
		content: { 'application/json': { schema: { $ref: '#/components/schemas/Report' } } }
	};
}

const NOT_FOUND = problemResponse('Report not found.');
const UNAUTHORIZED = problemResponse('Missing, invalid, or revoked API token.');
const VALIDATION = problemResponse(
	'Document validation failed (422); carries the actionable errors[].'
);
const CONFLICT = problemResponse('Concurrency or lifecycle conflict (409).');
const AI_DISABLED = problemResponse(
	'AI generation is disabled (503): no LLM endpoint is configured or the opt-in is absent. No outbound call is made.'
);
const AI_FAILED = problemResponse('The AI endpoint failed or returned unusable output (502).');
const RATE_LIMITED = problemResponse('Too many generation requests (429); retry after the hint.');

/** Builds the full OpenAPI 3.1 document. Pure (no I/O), so the validity gate calls it directly. */
export function buildOpenApiDocument(): Record<string, unknown> {
	return {
		openapi: '3.1.0',
		info: {
			title: 'Acta Diurna API',
			version: '1',
			description:
				'Programmatic report authoring and publishing. Every endpoint is a thin adapter over the same service layer the workspace uses, so the API and the workspace behave identically (FR30 parity).'
		},
		servers: [{ url: '/api/v1' }],
		security: [{ patBearer: [] }],
		components: {
			securitySchemes: {
				patBearer: {
					type: 'http',
					scheme: 'bearer',
					description: 'A personal access token (D10): `Authorization: Bearer acta_pat_...`.'
				}
			},
			schemas: {
				Document: documentComponent(),
				Report: reportSchema(),
				ReportSummary: reportSummarySchema(),
				Problem: problemSchema(),
				DataSet: dataSetSchema(),
				BlockDiagnostic: blockDiagnosticSchema(),
				BindingSummary: bindingSummarySchema(),
				DataPushResponse: dataPushResponseSchema(),
				SchemaResponse: schemaResponseSchema(),
				Outline: outlineSchema(),
				GenerateOutlineResponse: generateOutlineResponseSchema(),
				GenerateOutlineRequest: {
					type: 'object',
					required: ['intent'],
					description:
						'The narrative intent to draft an outline for, optionally grounded on a skeleton and/or a data set.',
					properties: {
						intent: { type: 'string', description: 'What the report should cover.' },
						skeletonId: { type: 'string', format: 'uuid' },
						dataSetId: { type: 'string', format: 'uuid' }
					}
				},
				GenerateFillRequest: {
					type: 'object',
					required: ['outline', 'outlineHash'],
					description:
						'The approved outline and its hash (from /reports/generate/outline). With a `reportId` the matching draft is filled in place; without one a fresh draft is seeded.',
					properties: {
						outline: { $ref: '#/components/schemas/Outline' },
						outlineHash: {
							type: 'string',
							description: 'The hash returned alongside the outline; a mismatch is a 409.'
						},
						reportId: { type: 'string', format: 'uuid' },
						skeletonId: { type: 'string', format: 'uuid' },
						dataSetId: { type: 'string', format: 'uuid' },
						expectedUpdatedAt: {
							type: 'string',
							format: 'date-time',
							description:
								'The `updatedAt` the caller last saw on the target report; a mismatch is a 409.'
						}
					}
				},
				CreateReportRequest: {
					type: 'object',
					description:
						'Either an initial `document` (instantiated as-is) or an optional `title` for a blank starter draft.',
					properties: {
						title: { type: 'string' },
						document: { $ref: '#/components/schemas/Document' }
					}
				},
				UpdateReportRequest: {
					type: 'object',
					description:
						'A partial update; provide at least one of `title` or `document`. `expectedUpdatedAt` opts into optimistic concurrency.',
					properties: {
						title: { type: 'string' },
						document: { $ref: '#/components/schemas/Document' },
						expectedUpdatedAt: {
							type: 'string',
							format: 'date-time',
							description: 'The `updatedAt` the caller last saw; a mismatch is a 409.'
						}
					}
				},
				PublishRequest: {
					type: 'object',
					description:
						'Optional body; `expectedUpdatedAt` opts into the optimistic-concurrency 409.',
					properties: {
						expectedUpdatedAt: { type: 'string', format: 'date-time' }
					}
				}
			}
		},
		paths: {
			'/reports': {
				get: {
					summary: 'List reports',
					operationId: 'listReports',
					description:
						'Lists a page of reports, newest first. Keyset (cursor) paginated: pass the prior ' +
						'response `nextCursor` back as `?cursor=` to fetch the next page; a null `nextCursor` ' +
						'is the last page. `?limit=` sets the page size (clamped server-side).',
					parameters: [
						{
							name: 'cursor',
							in: 'query',
							required: false,
							description: 'An opaque page cursor from a prior response `nextCursor`.',
							schema: { type: 'string' }
						},
						{
							name: 'limit',
							in: 'query',
							required: false,
							description: 'The page size; clamped to the server maximum.',
							schema: { type: 'integer', minimum: 1, maximum: 500 }
						}
					],
					responses: {
						'200': {
							description: 'A page of reports, newest first, with the cursor for the next page.',
							content: {
								'application/json': {
									schema: {
										type: 'object',
										required: ['items', 'nextCursor'],
										properties: {
											items: {
												type: 'array',
												items: { $ref: '#/components/schemas/ReportSummary' }
											},
											nextCursor: {
												type: ['string', 'null'],
												description:
													'The cursor to fetch the next page, or null when this is the last page.'
											}
										}
									}
								}
							}
						},
						'401': UNAUTHORIZED
					}
				},
				post: {
					summary: 'Create a report',
					operationId: 'createReport',
					requestBody: {
						required: false,
						content: {
							'application/json': { schema: { $ref: '#/components/schemas/CreateReportRequest' } }
						}
					},
					responses: {
						'201': reportResponse('The created draft report.'),
						'400': problemResponse('Malformed request body.'),
						'401': UNAUTHORIZED,
						'422': VALIDATION
					}
				}
			},
			'/reports/{id}': {
				parameters: [
					{
						name: 'id',
						in: 'path',
						required: true,
						schema: { type: 'string', format: 'uuid' }
					}
				],
				get: {
					summary: 'Get a report',
					operationId: 'getReport',
					responses: {
						'200': reportResponse('The report.'),
						'401': UNAUTHORIZED,
						'404': NOT_FOUND
					}
				},
				patch: {
					summary: 'Update a report',
					operationId: 'updateReport',
					requestBody: {
						required: true,
						content: {
							'application/json': { schema: { $ref: '#/components/schemas/UpdateReportRequest' } }
						}
					},
					responses: {
						'200': reportResponse('The updated report.'),
						'400': problemResponse('Malformed or empty request body.'),
						'401': UNAUTHORIZED,
						'404': NOT_FOUND,
						'409': CONFLICT,
						'422': VALIDATION
					}
				},
				delete: {
					summary: 'Delete a draft report',
					operationId: 'deleteReport',
					responses: {
						'204': { description: 'The draft was deleted.' },
						'401': UNAUTHORIZED,
						'404': NOT_FOUND,
						'409': problemResponse('The report is published and cannot be deleted.')
					}
				}
			},
			'/reports/{id}/publish': {
				parameters: [
					{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }
				],
				post: {
					summary: 'Publish a report',
					operationId: 'publishReport',
					requestBody: {
						required: false,
						content: {
							'application/json': { schema: { $ref: '#/components/schemas/PublishRequest' } }
						}
					},
					responses: {
						'200': reportResponse('The published report.'),
						'401': UNAUTHORIZED,
						'404': NOT_FOUND,
						'409': CONFLICT,
						'422': VALIDATION
					}
				}
			},
			'/reports/{id}/duplicate': {
				parameters: [
					{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }
				],
				post: {
					summary: 'Duplicate a report into a fresh draft',
					operationId: 'duplicateReport',
					description:
						'Mints a fresh draft from a deep copy of the source report (FR10), the same service the workspace Duplicate action uses. A published source is duplicated into an editable draft. Returns the new draft (201).',
					responses: {
						'201': reportResponse('The duplicated draft report.'),
						'401': UNAUTHORIZED,
						'404': NOT_FOUND
					}
				}
			},
			'/reports/{id}/unpublish': {
				parameters: [
					{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }
				],
				post: {
					summary: 'Unpublish a report back to draft',
					operationId: 'unpublishReport',
					responses: {
						'200': reportResponse('The report, reverted to draft.'),
						'401': UNAUTHORIZED,
						'404': NOT_FOUND
					}
				}
			},
			'/reports/generate/outline': {
				post: {
					summary: 'Propose a report outline (outline-first generation, stage 1)',
					operationId: 'generateOutline',
					description:
						'From an `intent` (optionally grounded on a skeleton and/or data set) the configured LLM proposes a bounded, reviewable outline (FR32). Returns the outline plus its content hash; approve the outline, then post it back with the hash to `/reports/generate/outline` -> `/reports/generate/fill`. Both AI gates apply: a disabled instance returns 503 and makes NO outbound call. The flow is owner-scoped to the calling token. Writes nothing.',
					requestBody: {
						required: true,
						content: {
							'application/json': {
								schema: { $ref: '#/components/schemas/GenerateOutlineRequest' }
							}
						}
					},
					responses: {
						'200': {
							description: 'The proposed outline and its approval hash.',
							content: {
								'application/json': {
									schema: { $ref: '#/components/schemas/GenerateOutlineResponse' }
								}
							}
						},
						'400': problemResponse('Malformed request body or empty intent.'),
						'401': UNAUTHORIZED,
						'429': RATE_LIMITED,
						'502': AI_FAILED,
						'503': AI_DISABLED
					}
				}
			},
			'/reports/generate/fill': {
				post: {
					summary: 'Fill an approved outline into a draft (outline-first generation, stage 2)',
					operationId: 'generateFill',
					description:
						'Fills the APPROVED `outline` (with its `outlineHash`) into a schema-valid draft through the same validate-on-write every surface uses. With a `reportId` it replaces that draft (200; a published report or stale `expectedUpdatedAt` is a 409); without one it seeds a fresh draft (201). A mismatched `outlineHash` is a 409 BEFORE any LLM call (the re-approval discipline); an invalid model document is a 422 with actionable errors[] and the draft is untouched. Both AI gates apply (503 when disabled). Owner-scoped to the calling token.',
					requestBody: {
						required: true,
						content: {
							'application/json': {
								schema: { $ref: '#/components/schemas/GenerateFillRequest' }
							}
						}
					},
					responses: {
						'200': reportResponse('The existing draft, filled in place.'),
						'201': reportResponse('A fresh draft seeded from the filled outline.'),
						'400': problemResponse('Malformed request body, or a missing outline / hash.'),
						'401': UNAUTHORIZED,
						'404': NOT_FOUND,
						'409': problemResponse(
							'A stale/edited outline (the hash no longer matches), a published target, or a stale concurrency token (409).'
						),
						'422': VALIDATION,
						'429': RATE_LIMITED,
						'502': AI_FAILED,
						'503': AI_DISABLED
					}
				}
			},
			'/whoami': {
				get: {
					summary: 'Identify the authenticated token',
					operationId: 'whoami',
					description: 'Returns the id of the PAT the caller authenticated with (4.1).',
					responses: {
						'200': {
							description: 'The authenticated token id.',
							content: {
								'application/json': {
									schema: {
										type: 'object',
										required: ['tokenId'],
										properties: { tokenId: { type: ['string', 'null'] } }
									}
								}
							}
						},
						'401': UNAUTHORIZED
					}
				}
			},
			'/data-sets': {
				post: {
					summary: 'Push a data set onto a report',
					operationId: 'pushDataSet',
					description:
						'Pushes raw file bytes (the request body) through the SAME ingestion + binding pipeline the workspace upload uses (FR13). The format comes from `Content-Type` (`text/csv` or `application/json`; an Excel content-type gets the honest 415). With `?reportId` the push auto-rebinds the target draft report and returns the per-block diagnostics + binding summary (FR14/15 parity); without it the data set is stored unbound. The 50 MB cap is enforced before the body is read.',
					parameters: [
						{
							name: 'reportId',
							in: 'query',
							required: false,
							description: 'The target draft report to bind the data set onto.',
							schema: { type: 'string', format: 'uuid' }
						},
						{
							name: 'X-Filename',
							in: 'header',
							required: false,
							description:
								'A label for the data set (metadata only; bytes are stored under a UUID).',
							schema: { type: 'string' }
						}
					],
					requestBody: {
						required: true,
						description: 'The raw file bytes; the format is taken from `Content-Type`.',
						content: {
							'text/csv': { schema: { type: 'string' } },
							'application/json': { schema: { type: 'string' } }
						}
					},
					responses: {
						'201': {
							description:
								'The stored data set; the diagnostics, summary, and rebound block ids are present when a report was targeted.',
							content: {
								'application/json': {
									schema: { $ref: '#/components/schemas/DataPushResponse' }
								}
							}
						},
						'400': problemResponse('Malformed request (empty body or bad `reportId`).'),
						'401': UNAUTHORIZED,
						'404': problemResponse('The target report was not found.'),
						'409': problemResponse('The target report is published (binding targets a draft).'),
						'413': problemResponse('The body exceeds the 50 MB upload cap.'),
						'415': problemResponse(
							'Unsupported Content-Type (Excel is not supported; use CSV or JSON).'
						),
						'422': problemResponse('The file could not be parsed (encoding/format).')
					}
				}
			},
			'/schema': {
				get: {
					summary: 'Fetch the published document schema',
					operationId: 'getSchema',
					description:
						'Returns the published JSON Schema (draft 2020-12) of the current document version, with the minimal and full example documents (AR2; FR31). PUBLIC - no PAT required - as a discovery surface that leaks no report data. Cacheable per version.',
					security: [],
					responses: {
						'200': {
							description: 'The published schema and its examples.',
							headers: {
								'Cache-Control': {
									description: 'The schema is immutable per version.',
									schema: { type: 'string' }
								}
							},
							content: {
								'application/json': {
									schema: { $ref: '#/components/schemas/SchemaResponse' }
								}
							}
						}
					}
				}
			}
		},
		'x-acta-schema-version': CURRENT_SCHEMA_VERSION
	};
}
