/**
 * OpenAPI 3.1 description of the `/api/v1` surface (D8). HAND-ASSEMBLED rather
 * than generated by a zod-to-openapi dependency (CLAUDE.md "no new dependencies"
 * + the backlog/4.2 recommendation): OpenAPI 3.1 is a JSON Schema 2020-12
 * superset, so the LARGE complex schema - the document - is referenced straight
 * from the existing `toJsonSchema()` export (story 1.2, `static/schema/v1.json`)
 * with NO translation. The small, stable request/response wrappers (the report
 * resource, the create/update payloads, the RFC 9457 Problem shape) are written
 * here; hand-writing them is less code and zero dependency than wiring a
 * generator, and the document schema stays the single source of truth.
 *
 * Served at `/api/v1/openapi.json` as a PUBLIC discovery surface (no PAT): the
 * spec is the API's self-description and leaks no report data, consistent with
 * the 4.3 public `/api/v1/schema`. The endpoints it describes are all
 * bearer-authenticated (the `patBearer` security scheme, D10).
 */
import { CURRENT_SCHEMA_VERSION, toJsonSchema } from '$lib/schema';

const REPORT_STATUS = { type: 'string', enum: ['draft', 'published'] } as const;

/** The report resource as serialized by the endpoints (Dates become ISO strings over JSON). */
function reportSchema(): Record<string, unknown> {
	return {
		type: 'object',
		required: ['id', 'title', 'status', 'schemaVersion', 'document', 'createdAt', 'updatedAt'],
		properties: {
			id: { type: 'string', format: 'uuid' },
			title: { type: 'string' },
			status: REPORT_STATUS,
			schemaVersion: { type: 'integer' },
			document: { $ref: '#/components/schemas/Document' },
			publishedDocument: {
				oneOf: [{ $ref: '#/components/schemas/Document' }, { type: 'null' }]
			},
			publishedAt: { type: ['string', 'null'], format: 'date-time' },
			createdAt: { type: 'string', format: 'date-time' },
			updatedAt: { type: 'string', format: 'date-time' }
		}
	};
}

function reportSummarySchema(): Record<string, unknown> {
	return {
		type: 'object',
		required: ['id', 'title', 'status', 'updatedAt'],
		properties: {
			id: { type: 'string', format: 'uuid' },
			title: { type: 'string' },
			status: REPORT_STATUS,
			updatedAt: { type: 'string', format: 'date-time' }
		}
	};
}

/** RFC 9457 problem+json (D9), including the FR2 actionable `errors[]` (block path/field/hint). */
function problemSchema(): Record<string, unknown> {
	return {
		type: 'object',
		description: 'RFC 9457 problem details (application/problem+json).',
		required: ['type', 'title', 'status'],
		properties: {
			type: { type: 'string' },
			title: { type: 'string' },
			status: { type: 'integer' },
			detail: { type: 'string' },
			errors: {
				type: 'array',
				description:
					'Actionable validation errors (FR2): the failing block path, field, and a fix hint.',
				items: {
					type: 'object',
					required: ['path', 'message'],
					properties: {
						path: { type: 'string', description: 'e.g. sections[2].blocks[0].alt' },
						message: { type: 'string' },
						hint: { type: 'string' }
					}
				}
			}
		}
	};
}

/** The document component: the published JSON Schema export, embedded directly (no $ref rewrite needed - it is fully inlined). */
function documentComponent(): Record<string, unknown> {
	const { $schema: _dialect, ...schema } = toJsonSchema();
	void _dialect;
	return schema;
}

function problemResponse(description: string): Record<string, unknown> {
	return {
		description,
		content: { 'application/problem+json': { schema: { $ref: '#/components/schemas/Problem' } } }
	};
}

function reportResponse(description: string): Record<string, unknown> {
	return {
		description,
		content: { 'application/json': { schema: { $ref: '#/components/schemas/Report' } } }
	};
}

const NOT_FOUND = problemResponse('Report not found.');
const UNAUTHORIZED = problemResponse('Missing, invalid, or revoked API token.');
const VALIDATION = problemResponse(
	'Document validation failed (422); carries the actionable errors[].'
);
const CONFLICT = problemResponse('Concurrency or lifecycle conflict (409).');

/** Builds the full OpenAPI 3.1 document. Pure (no I/O), so the validity gate calls it directly. */
export function buildOpenApiDocument(): Record<string, unknown> {
	return {
		openapi: '3.1.0',
		info: {
			title: 'Acta Diurna API',
			version: '1',
			description:
				'Programmatic report authoring and publishing. Every endpoint is a thin adapter over the same service layer the workspace uses, so the API and the workspace behave identically (FR30 parity).'
		},
		servers: [{ url: '/api/v1' }],
		security: [{ patBearer: [] }],
		components: {
			securitySchemes: {
				patBearer: {
					type: 'http',
					scheme: 'bearer',
					description: 'A personal access token (D10): `Authorization: Bearer acta_pat_...`.'
				}
			},
			schemas: {
				Document: documentComponent(),
				Report: reportSchema(),
				ReportSummary: reportSummarySchema(),
				Problem: problemSchema(),
				CreateReportRequest: {
					type: 'object',
					description:
						'Either an initial `document` (instantiated as-is) or an optional `title` for a blank starter draft.',
					properties: {
						title: { type: 'string' },
						document: { $ref: '#/components/schemas/Document' }
					}
				},
				UpdateReportRequest: {
					type: 'object',
					description:
						'A partial update; provide at least one of `title` or `document`. `expectedUpdatedAt` opts into optimistic concurrency.',
					properties: {
						title: { type: 'string' },
						document: { $ref: '#/components/schemas/Document' },
						expectedUpdatedAt: {
							type: 'string',
							format: 'date-time',
							description: 'The `updatedAt` the caller last saw; a mismatch is a 409.'
						}
					}
				},
				PublishRequest: {
					type: 'object',
					description:
						'Optional body; `expectedUpdatedAt` opts into the optimistic-concurrency 409.',
					properties: {
						expectedUpdatedAt: { type: 'string', format: 'date-time' }
					}
				}
			}
		},
		paths: {
			'/reports': {
				get: {
					summary: 'List reports',
					operationId: 'listReports',
					responses: {
						'200': {
							description: 'The reports, newest first, in a forward-compatible envelope.',
							content: {
								'application/json': {
									schema: {
										type: 'object',
										required: ['items'],
										properties: {
											items: {
												type: 'array',
												items: { $ref: '#/components/schemas/ReportSummary' }
											}
										}
									}
								}
							}
						},
						'401': UNAUTHORIZED
					}
				},
				post: {
					summary: 'Create a report',
					operationId: 'createReport',
					requestBody: {
						required: false,
						content: {
							'application/json': { schema: { $ref: '#/components/schemas/CreateReportRequest' } }
						}
					},
					responses: {
						'201': reportResponse('The created draft report.'),
						'400': problemResponse('Malformed request body.'),
						'401': UNAUTHORIZED,
						'422': VALIDATION
					}
				}
			},
			'/reports/{id}': {
				parameters: [
					{
						name: 'id',
						in: 'path',
						required: true,
						schema: { type: 'string', format: 'uuid' }
					}
				],
				get: {
					summary: 'Get a report',
					operationId: 'getReport',
					responses: {
						'200': reportResponse('The report.'),
						'401': UNAUTHORIZED,
						'404': NOT_FOUND
					}
				},
				patch: {
					summary: 'Update a report',
					operationId: 'updateReport',
					requestBody: {
						required: true,
						content: {
							'application/json': { schema: { $ref: '#/components/schemas/UpdateReportRequest' } }
						}
					},
					responses: {
						'200': reportResponse('The updated report.'),
						'400': problemResponse('Malformed or empty request body.'),
						'401': UNAUTHORIZED,
						'404': NOT_FOUND,
						'409': CONFLICT,
						'422': VALIDATION
					}
				},
				delete: {
					summary: 'Delete a draft report',
					operationId: 'deleteReport',
					responses: {
						'204': { description: 'The draft was deleted.' },
						'401': UNAUTHORIZED,
						'404': NOT_FOUND,
						'409': problemResponse('The report is published and cannot be deleted.')
					}
				}
			},
			'/reports/{id}/publish': {
				parameters: [
					{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }
				],
				post: {
					summary: 'Publish a report',
					operationId: 'publishReport',
					requestBody: {
						required: false,
						content: {
							'application/json': { schema: { $ref: '#/components/schemas/PublishRequest' } }
						}
					},
					responses: {
						'200': reportResponse('The published report.'),
						'401': UNAUTHORIZED,
						'404': NOT_FOUND,
						'409': CONFLICT,
						'422': VALIDATION
					}
				}
			},
			'/reports/{id}/unpublish': {
				parameters: [
					{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }
				],
				post: {
					summary: 'Unpublish a report back to draft',
					operationId: 'unpublishReport',
					responses: {
						'200': reportResponse('The report, reverted to draft.'),
						'401': UNAUTHORIZED,
						'404': NOT_FOUND
					}
				}
			},
			'/whoami': {
				get: {
					summary: 'Identify the authenticated token',
					operationId: 'whoami',
					description: 'Returns the id of the PAT the caller authenticated with (4.1).',
					responses: {
						'200': {
							description: 'The authenticated token id.',
							content: {
								'application/json': {
									schema: {
										type: 'object',
										required: ['tokenId'],
										properties: { tokenId: { type: ['string', 'null'] } }
									}
								}
							}
						},
						'401': UNAUTHORIZED
					}
				}
			}
		},
		'x-acta-schema-version': CURRENT_SCHEMA_VERSION
	};
}
